language: python
dist: bionic
sudo: required
python:
  - 3.6
  - 3.7
  - 3.8
services:
  - postgresql
install:
  - pip install pipenv
  - pipenv install --deploy --dev
env:
  - SECRET_KEY='pipo' EMAIL_HOST_PASSWORD='pipo' POSTGRES_HOST='localhost' POSTGRES_PASSWORD='' RAVEN=True DSN=''
script:
  - python -Wa manage.py migrate
  - PYTHONWARNINGS=always coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - mypy .
  - pydocstyle
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=videgrenier"
after_success:
  - coveralls
