language: python
python:
  - 3.6
env:
  - SECRET_KEY=pipo
install:
  - pip install -r requirements.txt flake8 python-coveralls safety
script:
  - ./manage.py migrate
  - coverage run manage.py test
  - flake8 .
  - safety check
after_success:
  - coveralls
