version: '3'

networks:
  web:
    external: true

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/videgrenier/sql:/var/lib/postgresql/data

  memcached:
    image: memcached:alpine
    restart: unless-stopped

  app:
    build: .
    restart: unless-stopped
    environment:
      - DB=postgres
      - MEMCACHED=True
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/videgrenier/srv:/srv
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: videgrenier.${DOMAIN_NAME:-localhost}"

  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/videgrenier/srv:/srv:ro
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: videgrenier.${DOMAIN_NAME:-localhost}; PathPrefix: /static, /media"
    networks:
      - web
